app:
  verbose: true
  debug: true
logger:
  hooks:
    - stackdriver
    - kinesis
    - syslog
aws:
  access_key_id: ==AES32==+NPjNiwCtTNvMUg94O/PVGOPc1N6ExBx7Lyz3TGRuIqVfqFoYuRNEl1gkZw=
  secret_access_key: ==AES32==onXRqpVtlebXW+dN5atvjpZGuyNH8pzkAD7tx7diCj9rnByX9+BxlESV1ehoo7D7BtoDCDf73uLYVqXDQvdOq5JoL9AAFdIr
  region: us-east-1
  sts_account: 122130270846
  sts_role: rai
  sts_role_duration_seconds:  1h
googlecloud:
  type: ==AES32==PT1BRVMzMj09WYsXB91tmihKV8qdiVaUhn1Vye2UqKHVoiNd+l1RWAYuyk1E
  project_id: ==AES32==PT1BRVMzMj09+RxoghN8HHbVy7v/kLdEwPHOoF4ZcX7E7A2R8uk40bXb5BleLUxK8A==
  private_key_id: ==AES32==PT1BRVMzMj09sjNSwJuqLN/M6CrC5FmZM4OyyeQigp9sp9YEDFbwsRnPWEhj8VG5yinml3v7TajNfckm21pJJaMam0Ih6jvAY82ewO07r26G
  private_key: ==AES32==PT1BRVMzMj09vXwEA0af0jxR3Dr5sgCB11XZmg6gisuiKrOaN5P7fRHZpvDlQsdbBtdcEHZyI5wRGAT5Lu1DNTt0ksPEXoB4aqbNmM0DNH80nyHz+nTFeHHDTWHdX94/3VCUjV0aUCLlJOwnNUopj/8FSQ5KnsDv/50WShRAsDUIs+itkoe4YPXYmTmN71BvtNc+0Al2ZIBGyyATU0plYu/a5oHl91r/bK1/0HaFJz/pqhGLtt6XMx+bZTGaVZDZgs0XK8LyFmMgf2bah31md3PZqkXVjKM3BcWdehLrXsaOS0opl+5YPGzri16/cRGHaXts1wNdVendJR93MCOLoCcGPbIEuOVAGfnZVe59JAMQ06fVOQC+rciTZkvjfKwsJ5ZvV7nnunmxIWnJQ7zteQd6Vb00Kb5O93xztFu5HP+yWemLCK47MaSEIW1IYHX5oBLCZlUssjWCXgpdm9xXWALcodMWtX/LLswe/qzW9v5zZBb0i4xDwqJ6scgR+qnV0gu0u0p5a+3CKO6EK5SIU6SlKmyBIYNbT3n19SyXR1Pp/PiZQMqqcpYs81bS+qolX1aMT8tJD10Y6Koam1F7YGa15PgpcCE9l7ZDYYLoLXMyMS9ladtD8dbHu55vdGyRsXlYMhmiGhjPhajs3bAqIEXGpXuzBuVtTIH2MOSFBCerchwZzgn6srn8bU2/CnW2mIEnPcafIJvqLrL1MTMc9634Lv21+XrWm+9bYkPGwYMRKFm1x1k5AQkzeV+1pVt/ddGFWjUFxc1mTb0qqIoseFCFq9Vv6NIkS3L9fdmmTx7gdWkfVMJF6tDxVx9RLv6bc72SAZXUuHhnFb8kDQmUocZ8KVT94wmglEhjRXcwMeti0+U8nrL+HZrvLQqm0tIbDeKR3OZh8ZtDsfCktOHOeWGptOhBgMy6QXqjpz/ATl0+PzghwRHbEWAMLm3MsiXUo9tA9xSf5fLMwPUXOMc6gS9jx8AX6HEMP7BEC1csH44eavMP5JGincazpXiTha7rh2PzMA0Z1h+cQavElAfA6CjN+lwgGsYRlKJsa8g4kex5UDNyLAo9UrMjavO8ZSIiy0QN0/AuabJ8Iv8Nh5OUCLr//k9h4NdHI2po6S5Er/SoE0+jy8BinPtFS6ufDNIPY6ePlbxfAlQktSO4s4D5Hk5XMhb64PIv+liAFmpdjs3p4MVo+03XawBW4CbrOgh3b4BsbdjH+NKY+Yon/gamu5YKipHmHY1fQ0JwTLbQc6Iv0fcFX15vUVzcEWnFO3Sg9OjyXrhYx1qsbqT76ApovtcYTZNsP1TwILzhu+LD3l4usPasmqwyLvuBQn3guQQcx0x6F6MoVLMspSmhuco2yqPhB5yM2PcGS45OfktaoPyLZZJwYial2kbEdDK8cVw4VOJ1TXsqUxaJ8VLI2577TFZFfxVF9FlpzmElmAdxKesp/hEzFPKSiCqVBkw22VPZxer0lnuTBbCUtWj4QXSZhvnuFVa2akcmevCmin/u/3mwqhxVU5Xn/FuqenvbRVAxh6YWDK/qrgZGfrpPx3ObxC+HOKsfpUQ+urR7NyXuvtJw71j+KLu1YS5yIBT3qInGcPPgNrlD232nKqG8dUb+++jI3yan4dchyfiUA+LMeUbYIlie76s+3qfYsy7Bdq3btTsVvimg1PbCdZfd020dLLsZy/HIdwa6HVi+kH8jyNqux3xRKmZ5dwd/gq8DOidp4HUhP9oBrB3TLw6yn13jowXKq5zHsQLVJwsr6h/Y113k9NQgnftnv6i0RS5l2Og80zsGLDMlE8eP2KDwnau08myWtK1nHvGvuQC6/ucsx5ZM5ENCW5mEyMYzaNW/fGMVVV7Er2O2ji0N5EvoDhXvMTgReVxr6xigmoR29UGJPGqBpQdW+sUfJkYtzGdn0GhHWQ0C8x94mnlnfDJjJwWGwSb4xlT9ZLHAc4CJS1lFVNN02TH8pbDf/znxX0K/JQ5ZYvDG8HuAA4GqdmeDkpHPPkjhxOZgWN6hfws2T/zR3IhxPz1FZ/lBslvYy54ldwa0+LaGtDs28Jig70oHudtamNr49JzIIXfl1T0en/dz16eCnonhCW/8AdxQrxXm7PAwrEBa17vIH/MNgwnW0VeZvRU2nw+1KQ7xAfSb4jLvZ3LSMgKMaEZEcU8VrTXCwldDRsm5Qum4edmrfdqt7WaworG1RrnxYdc7QKtt5+LdiiJK6HUtcLGuuPdwKzhyxxwXFrEaKnN7Mh4isXos9bUfAJWaF47tfotlwTxcmTarMjVRzq6H/Px5fh0N33A3HuM1uatu96lT3/YU54nY7jZi06THUT1zpW6wJWa9o4dMVmqf5jB6o5Ghl3KzbLceZpSHzke0TPs3HEvBR9VA+NoPfWYoDBz9bIHrZgk8RNNCZa6WoAaW6/46VHJiwKAz71N7N/4yNFILDPIFfNigT0niQsm+Dq/yAi9W/tlOQIPPbv67kSPq+4VNkzhHC4ruZOdUhdNvIEt5SlA+y5/+4fNuVD2mhozxEAajpMFFXJ+gxldH2RugkH2s5A/n9vOXQxw17dBmplx5GhE63ldrVxGrdq8J0UXfyWSzJtZshN2s2lWNsVBgf9uDV89s7gHCebLk2+e8X192CkvQmUvGghCB8cUeToqrZhar2XpOXAgR7+Lh3daYqCDlEWRKVFpG4ihT44GvvxRBdfqEvvnA09ccS2QpbQHBO1oSqCwPYOQzklmSzD2rdPCWBQLRxEDLi7ggBi1PlM6iiZOzMbujzyxFF/gXqZuYmpsdNqxia4i7f9L3DhKRw+W1mBM4BBhcNCRaU2QsH5qgPCSJrbGE5iE4EBBvMhu9dL1nHZJrtBZZM1tv+SA6lPJrPjq+dnQfuECDOcpjZpsYGdtauXjE1oFp2d7AAguUPU5QHcDcdpgpOyaSSLtzPINMZq5onX+z0hEq1X2RKaFJLLNGCHFfQP8CdurcQII4W5rgn8d/IfnYHzCJLXZRE/HQnMFnKJhYYNYz/VFeQGGKKLNyqZe1Gn43MrxMjLz1O1W9MIO4/w7bghnhCLvyclxV83n+Dv+5EVsOEzJoAOZCHhvAvK/Y50OzkJP11LSf/Uf9lwAhfDxylImy
  client_email: ==AES32==PT1BRVMzMj09ALW3T3vu+XI3nXc1JB4nmAXFqeU6ry4qIJMp5dYcML229Fr/t0Mi/rVq88341tBTtoDhiDVhZa05jj6GSoiXkB1K4QlGA/Mh8PqiUQWICxu38+9D
  client_id: ==AES32==PT1BRVMzMj094BEi9qehgmV5x9jiEDWan3kLBKb2umd8tjHwkSWVHb5aVeJURKbDuHiPUnE=
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://accounts.google.com/o/oauth2/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: ==AES32==PT1BRVMzMj09mvGnPL2RpGsxpSjRiyQbPVrAJo7GiloahdHzssI50qbA91l9jv120ozge/f+KADQ3LXtN41LVhDlF88wf6+n89nmENwZWUnhnnQHM05NQaCzpQDyBZ/DU1wPSeFsKF/cm859c0Y0BNYHtZcYOK2PiTKNYULye5AkNA2mfS9zOjic5X/VeImxNUGn9cRP8j8Mj9vTGWiCM5aoXgSG
store:
  provider: s3
  base_url: http://s3.amazonaws.com
  acl: public-read
broker:
  provider: sqs
  serializer: json
  autoack: true
client:
  name: rai
  upload_bucket: files.rai-project.com
  bucket: userdata
  build_file: rai_build
auth:
  provider: auth0
  domain: raiproject.auth0.com
  client_id: ==AES32==6hfPO1LiIUGaAut6mdg2Zb9ggGKutPOF
  client_secret: ==AES32==GtEMfdOuG2aQraS3COa-jKQLZftaAIzDZcsqamCt1tr0i5YhH-RY_7G6S8vKzWs-
pubsub:
  endpoints:
    - pubsub.rai-project.com:6379
  password: ==AES32==SnY+X9yvTpvVRWo+hqq1Bjup8vvYEtDURcsO2w==

