app:
  verbose: true
  debug: true
logger:
  hooks:
    - stackdriver
    - kinesis
    - syslog
    - graylog
graylog:
  address: 34.199.189.82
  port: 12201
aws:
  access_key_id: ==AES32==PT1BRVMzMj094kOWYqYJ7IqWA7blVUTfxWdlkq9jJjDAVTTR0ZsXGgBXIbVSWPhlFz1mH7o=
  secret_access_key: ==AES32==PT1BRVMzMj09fISTFEtXHbTnpMDwiEv8Jn/Gxc6jJFOVgK0J6rncEwXzIs6EhJeYuI6BaLYJ8DmE7xsh4Pfqfy0RkHn8F2oGg08Vg/thMfQG
  region: us-east-1
store:
  provider: s3
  base_url: http://s3.amazonaws.com
  acl: public-read
broker:
  provider: sqs
  serializer: json
  autoack: true
client:
  name: rai
  upload_bucket: files.rai-project.com
  bucket: userdata
  build_file: rai_build
auth:
  provider: auth0
  domain: raiproject.auth0.com
  client_id: ==AES32==6hfPO1LiIUGaAut6mdg2Zb9ggGKutPOF
  client_secret: ==AES32==GtEMfdOuG2aQraS3COa-jKQLZftaAIzDZcsqamCt1tr0i5YhH-RY_7G6S8vKzWs-
pubsub:
  endpoints:
    - pubsub.rai-project.com:6379
  password: ==AES32==SnY+X9yvTpvVRWo+hqq1Bjup8vvYEtDURcsO2w==

